FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln ./
COPY OrderProcessingService.API/*.csproj OrderProcessingService.API/              
COPY OrderProcessingService.Worker/*.csproj OrderProcessingService.Worker/
COPY OrderProcessingService.Application/*.csproj OrderProcessingService.Application/
COPY OrderProcessingService.Domain/*.csproj OrderProcessingService.Domain/
COPY OrderProcessingService.Infrastructure/*.csproj OrderProcessingService.Infrastructure/


RUN dotnet restore

COPY . .

RUN dotnet publish OrderProcessingService.Worker/OrderProcessingService.Worker.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "OrderProcessingService.Worker.dll"]
