services:
  ### 🔹 Banco de Dados MongoDB ###
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db

  ### 🔹 RabbitMQ (Mensageria) ###
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  ### 🔹 API ###
  api:
    build:
      context: ..
      dockerfile: OrderProcessingService.API/Dockerfile
    container_name: order_api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://admin:secret@mongodb:27017
      - RabbitMQ__HostName=rabbitmq

volumes:
  mongo_data:
  rabbitmq_data: